class /EY1/CL_SAV_DEFERD_TAX_MPC definition
  public
  inheriting from /IWBEP/CL_MGW_PUSH_ABS_MODEL
  create public .

public section.

  interfaces IF_SADL_GW_MODEL_EXPOSURE_DATA .

  types:
   begin of ts_text_element,
      artifact_name  type c length 40,       " technical name
      artifact_type  type c length 4,
      parent_artifact_name type c length 40, " technical name
      parent_artifact_type type c length 4,
      text_symbol    type textpoolky,
   end of ts_text_element .
  types:
  begin of TS_GLOBALPARAMETER01,
     CONSOLIDATIONUNIT type C length 18,
     FISCALYEAR type C length 4,
     CONSOLIDATIONCHARTOFACCOUNTS type C length 2,
     CONSOLIDATIONGROUP type C length 18,
     INTENTION type C length 30,
     PERIODFROM type C length 3,
     PERIODTO type C length 3,
     LOCALCURRENCY type C length 5,
     LOCALCURRENCYTYPE type C length 5,
     GROUPCURRENCY type C length 5,
     GROUPCURRENCYTYPE type C length 5,
  end of TS_GLOBALPARAMETER01 .
  types:
         tt_text_elements type standard table of ts_text_element with key text_symbol .
  types:
TT_GLOBALPARAMETER type standard table of TS_GLOBALPARAMETER01 .
  types:
    begin of TS_XEY1XSAV_C_CNSLDTNJRNLENTRY.
      include type /EY1/SAV_C_CNSLDTNJRNLENTRY.
  types:
      generated_id type string,
      P_CONSOLIDATIONUNITHIERARCHY type FINCS_HRYID,
      P_CONSOLIDATIONPRFTCTRHIER type FINCS_HRYID,
      P_CONSOLIDATIONSEGMENTHIER type FINCS_HRYID,
      P_KEYDATE type SYDATE,
      T_CONSOLIDATIONUNITFORELIM type I_CNSLDTNUNITFORELIMINATIONT-CONSOLIDATIONUNITMDMTEXT,
      T_CONSOLIDATIONPRFTCTRFORELIM type I_CNSLDTNPROFITCENTERFORELIMT-ADDITIONALMASTERDATATEXT,
      T_CONSOLIDATIONSEGMENTFORELIM type I_CNSLDTNSEGMENTFORELIMT-ADDITIONALMASTERDATATEXT,
    end of TS_XEY1XSAV_C_CNSLDTNJRNLENTRY .
  types:
   TT_XEY1XSAV_C_CNSLDTNJRNLENTRY type standard table of TS_XEY1XSAV_C_CNSLDTNJRNLENTRY .
  types:
    begin of TS_XEY1XSAV_C_CNSLDTNJRNLENTR.
      include type /EY1/SAV_C_CNSLDTNJRNLENTRY.
  types:
      generated_id type string,
      P_CONSOLIDATIONUNITHIERARCHY type FINCS_HRYID,
      P_CONSOLIDATIONPRFTCTRHIER type FINCS_HRYID,
      P_CONSOLIDATIONSEGMENTHIER type FINCS_HRYID,
      P_KEYDATE type SYDATE,
      T_CONSOLIDATIONUNITFORELIM type I_CNSLDTNUNITFORELIMINATIONT-CONSOLIDATIONUNITMDMTEXT,
      T_CONSOLIDATIONPRFTCTRFORELIM type I_CNSLDTNPROFITCENTERFORELIMT-ADDITIONALMASTERDATATEXT,
      T_CONSOLIDATIONSEGMENTFORELIM type I_CNSLDTNSEGMENTFORELIMT-ADDITIONALMASTERDATATEXT,
    end of TS_XEY1XSAV_C_CNSLDTNJRNLENTR .
  types:
   TT_XEY1XSAV_C_CNSLDTNJRNLENTR type standard table of TS_XEY1XSAV_C_CNSLDTNJRNLENTR .
  types:
   TS_XEY1XSAV_C_CURRLOCALGROUPVH type /EY1/SAV_C_CURRLOCALGROUPVH .
  types:
   TT_XEY1XSAV_C_CURRLOCALGROUPVH type standard table of TS_XEY1XSAV_C_CURRLOCALGROUPVH .
  types:
    begin of TS_XEY1XSAV_C_DEFERREDTAXROLLF.
      include type /EY1/SAV_C_DEFERREDTAXROLLFRWD.
  types:
      generated_id type string,
      P_RBUNIT type FC_BUNIT,
      P_TOPERIOD type POPER,
      P_RYEAR type GJAHR,
      P_TAXINTENTION type ZZ1_TAXINTENTION,
    end of TS_XEY1XSAV_C_DEFERREDTAXROLLF .
  types:
   TT_XEY1XSAV_C_DEFERREDTAXROLLF type standard table of TS_XEY1XSAV_C_DEFERREDTAXROLLF .
  types:
    begin of TS_XEY1XSAV_C_DEFERREDTAXROLL.
      include type /EY1/SAV_C_DEFERREDTAXROLLFRWD.
  types:
      generated_id type string,
      P_RBUNIT type FC_BUNIT,
      P_TOPERIOD type POPER,
      P_RYEAR type GJAHR,
      P_TAXINTENTION type ZZ1_TAXINTENTION,
    end of TS_XEY1XSAV_C_DEFERREDTAXROLL .
  types:
   TT_XEY1XSAV_C_DEFERREDTAXROLL type standard table of TS_XEY1XSAV_C_DEFERREDTAXROLL .
  types:
    begin of TS_XEY1XSAV_C_FETCH_TAX_RATESP.
      include type /EY1/SAV_C_FETCH_TAX_RATES.
  types:
      P_TOPERIOD type POPER,
      P_RYEAR type GJAHR,
    end of TS_XEY1XSAV_C_FETCH_TAX_RATESP .
  types:
   TT_XEY1XSAV_C_FETCH_TAX_RATESP type standard table of TS_XEY1XSAV_C_FETCH_TAX_RATESP .
  types:
    begin of TS_XEY1XSAV_C_FETCH_TAX_RATEST.
      include type /EY1/SAV_C_FETCH_TAX_RATES.
  types:
      P_TOPERIOD type POPER,
      P_RYEAR type GJAHR,
    end of TS_XEY1XSAV_C_FETCH_TAX_RATEST .
  types:
   TT_XEY1XSAV_C_FETCH_TAX_RATEST type standard table of TS_XEY1XSAV_C_FETCH_TAX_RATEST .
  types:
    begin of TS_XEY1XSAV_C_INTENTIONSSTATUS.
      include type /EY1/SAV_C_INTENTIONSSTATUS.
  types:
      P_BUNIT type FC_BUNIT,
    end of TS_XEY1XSAV_C_INTENTIONSSTATUS .
  types:
   TT_XEY1XSAV_C_INTENTIONSSTATUS type standard table of TS_XEY1XSAV_C_INTENTIONSSTATUS .
  types:
    begin of TS_XEY1XSAV_C_INTENTIONSSTATU.
      include type /EY1/SAV_C_INTENTIONSSTATUS.
  types:
      P_BUNIT type FC_BUNIT,
    end of TS_XEY1XSAV_C_INTENTIONSSTATU .
  types:
   TT_XEY1XSAV_C_INTENTIONSSTATU type standard table of TS_XEY1XSAV_C_INTENTIONSSTATU .
  types:
   TS_XEY1XSAV_C_READINTENTVHTYPE type /EY1/SAV_C_READINTENTVH .
  types:
   TT_XEY1XSAV_C_READINTENTVHTYPE type standard table of TS_XEY1XSAV_C_READINTENTVHTYPE .
  types:
   TS_XEY1XSAV_C_RECON_ADJ_REASON type /EY1/SAV_C_RECON_ADJ_REASON .
  types:
   TT_XEY1XSAV_C_RECON_ADJ_REASON type standard table of TS_XEY1XSAV_C_RECON_ADJ_REASON .
  types:
   TS_XEY1XSAV_C_RECON_LEDGERTYPE type /EY1/SAV_C_RECON_LEDGER .
  types:
   TT_XEY1XSAV_C_RECON_LEDGERTYPE type standard table of TS_XEY1XSAV_C_RECON_LEDGERTYPE .
  types:
   TS_XEY1XSAV_I_ACCCLASSTEXTTYPE type /EY1/SAV_I_ACCCLASSTEXT .
  types:
   TT_XEY1XSAV_I_ACCCLASSTEXTTYPE type standard table of TS_XEY1XSAV_I_ACCCLASSTEXTTYPE .
  types:
   TS_XEY1XSAV_I_FSITEMTEXTTYPE type /EY1/SAV_I_FSITEMTEXT .
  types:
   TT_XEY1XSAV_I_FSITEMTEXTTYPE type standard table of TS_XEY1XSAV_I_FSITEMTEXTTYPE .
  types:
   TS_XEY1XSAV_I_GLACCTEXTTYPE type /EY1/SAV_I_GLACCTEXT .
  types:
   TT_XEY1XSAV_I_GLACCTEXTTYPE type standard table of TS_XEY1XSAV_I_GLACCTEXTTYPE .
  types:
   TS_XEY1XSAV_I_JOURNALENTRYITEM type /EY1/SAV_I_JOURNALENTRYITEM .
  types:
   TT_XEY1XSAV_I_JOURNALENTRYITEM type standard table of TS_XEY1XSAV_I_JOURNALENTRYITEM .
  types:
   TS_C_CNSLDTNCHARTOFACCOUNTSVHT type C_CNSLDTNCHARTOFACCOUNTSVH .
  types:
   TT_C_CNSLDTNCHARTOFACCOUNTSVHT type standard table of TS_C_CNSLDTNCHARTOFACCOUNTSVHT .
  types:
   TS_C_CNSLDTNCTRLGAREAVHTYPE type C_CNSLDTNCTRLGAREAVH .
  types:
   TT_C_CNSLDTNCTRLGAREAVHTYPE type standard table of TS_C_CNSLDTNCTRLGAREAVHTYPE .
  types:
   TS_C_CNSLDTNDOCUMENTTYPEVHTYPE type C_CNSLDTNDOCUMENTTYPEVH .
  types:
   TT_C_CNSLDTNDOCUMENTTYPEVHTYPE type standard table of TS_C_CNSLDTNDOCUMENTTYPEVHTYPE .
  types:
   TS_C_CNSLDTNFINSTMNTITEMVHTYPE type C_CNSLDTNFINSTMNTITEMVH .
  types:
   TT_C_CNSLDTNFINSTMNTITEMVHTYPE type standard table of TS_C_CNSLDTNFINSTMNTITEMVHTYPE .
  types:
   TS_C_CNSLDTNLEDGERVHTYPE type C_CNSLDTNLEDGERVH .
  types:
   TT_C_CNSLDTNLEDGERVHTYPE type standard table of TS_C_CNSLDTNLEDGERVHTYPE .
  types:
   TS_C_CNSLDTNPOSTINGLEVELVHTYPE type C_CNSLDTNPOSTINGLEVELVH .
  types:
   TT_C_CNSLDTNPOSTINGLEVELVHTYPE type standard table of TS_C_CNSLDTNPOSTINGLEVELVHTYPE .
  types:
   TS_C_CNSLDTNPROFITCENTERFORELI type C_CNSLDTNPROFITCENTERFORELIMVH .
  types:
   TT_C_CNSLDTNPROFITCENTERFORELI type standard table of TS_C_CNSLDTNPROFITCENTERFORELI .
  types:
   TS_C_CNSLDTNPROFITCENTERVHTYPE type C_CNSLDTNPROFITCENTERVH .
  types:
   TT_C_CNSLDTNPROFITCENTERVHTYPE type standard table of TS_C_CNSLDTNPROFITCENTERVHTYPE .
  types:
   TS_C_CNSLDTNSEGMENTFORELIMVHTY type C_CNSLDTNSEGMENTFORELIMVH .
  types:
   TT_C_CNSLDTNSEGMENTFORELIMVHTY type standard table of TS_C_CNSLDTNSEGMENTFORELIMVHTY .
  types:
   TS_C_CNSLDTNSEGMENTVHTYPE type C_CNSLDTNSEGMENTVH .
  types:
   TT_C_CNSLDTNSEGMENTVHTYPE type standard table of TS_C_CNSLDTNSEGMENTVHTYPE .
  types:
   TS_C_CNSLDTNUNITFORELIMINATION type C_CNSLDTNUNITFORELIMINATIONVH .
  types:
   TT_C_CNSLDTNUNITFORELIMINATION type standard table of TS_C_CNSLDTNUNITFORELIMINATION .
  types:
   TS_C_CNSLDTNUNITVALUEHELPTYPE type C_CNSLDTNUNITVALUEHELP .
  types:
   TT_C_CNSLDTNUNITVALUEHELPTYPE type standard table of TS_C_CNSLDTNUNITVALUEHELPTYPE .
  types:
   TS_C_CNSLDTNVERSIONVHTYPE type C_CNSLDTNVERSIONVH .
  types:
   TT_C_CNSLDTNVERSIONVHTYPE type standard table of TS_C_CNSLDTNVERSIONVHTYPE .
  types:
    begin of TS_I_CNSLDTNAPPORTIONMENTTYPE.
      include type I_CNSLDTNAPPORTIONMENT.
  types:
      T_CONSOLIDATIONAPPORTIONMENT type I_CNSLDTNAPPORTIONMENTT-CONSOLIDATIONAPPORTIONMENTTEXT,
    end of TS_I_CNSLDTNAPPORTIONMENTTYPE .
  types:
   TT_I_CNSLDTNAPPORTIONMENTTYPE type standard table of TS_I_CNSLDTNAPPORTIONMENTTYPE .
  types:
    begin of TS_I_CNSLDTNBILLINGTYPETYPE.
      include type I_CNSLDTNBILLINGTYPE.
  types:
      T_BILLINGDOCUMENTTYPE type I_CNSLDTNBILLINGTYPET-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNBILLINGTYPETYPE .
  types:
   TT_I_CNSLDTNBILLINGTYPETYPE type standard table of TS_I_CNSLDTNBILLINGTYPETYPE .
  types:
    begin of TS_I_CNSLDTNBUSINESSAREATYPE.
      include type I_CNSLDTNBUSINESSAREA.
  types:
      T_BUSINESSAREA type I_CNSLDTNBUSINESSAREAT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNBUSINESSAREATYPE .
  types:
   TT_I_CNSLDTNBUSINESSAREATYPE type standard table of TS_I_CNSLDTNBUSINESSAREATYPE .
  types:
    begin of TS_I_CNSLDTNCHARTOFACCOUNTSTYP.
      include type I_CNSLDTNCHARTOFACCOUNTS.
  types:
      T_CONSOLIDATIONCHARTOFACCOUNTS type I_CNSLDTNCHARTOFACCOUNTST-CONSOLIDATIONCHARTOFACCTSTEXT,
    end of TS_I_CNSLDTNCHARTOFACCOUNTSTYP .
  types:
   TT_I_CNSLDTNCHARTOFACCOUNTSTYP type standard table of TS_I_CNSLDTNCHARTOFACCOUNTSTYP .
  types:
   TS_I_CNSLDTNCHARTOFACCOUNTSTTY type I_CNSLDTNCHARTOFACCOUNTST .
  types:
   TT_I_CNSLDTNCHARTOFACCOUNTSTTY type standard table of TS_I_CNSLDTNCHARTOFACCOUNTSTTY .
  types:
    begin of TS_I_CNSLDTNCONTROLLINGAREATYP.
      include type I_CNSLDTNCONTROLLINGAREA.
  types:
      T_CONTROLLINGAREA type I_CNSLDTNCONTROLLINGAREAT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNCONTROLLINGAREATYP .
  types:
   TT_I_CNSLDTNCONTROLLINGAREATYP type standard table of TS_I_CNSLDTNCONTROLLINGAREATYP .
  types:
   TS_I_CNSLDTNCONTROLLINGAREATTY type I_CNSLDTNCONTROLLINGAREAT .
  types:
   TT_I_CNSLDTNCONTROLLINGAREATTY type standard table of TS_I_CNSLDTNCONTROLLINGAREATTY .
  types:
    begin of TS_I_CNSLDTNCOSTCENTERTYPE.
      include type I_CNSLDTNCOSTCENTER.
  types:
      T_COSTCENTER type I_CNSLDTNCOSTCENTERT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNCOSTCENTERTYPE .
  types:
   TT_I_CNSLDTNCOSTCENTERTYPE type standard table of TS_I_CNSLDTNCOSTCENTERTYPE .
  types:
    begin of TS_I_CNSLDTNCOUNTRYTYPE.
      include type I_CNSLDTNCOUNTRY.
  types:
      T_COUNTRY type I_CNSLDTNCOUNTRYT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNCOUNTRYTYPE .
  types:
   TT_I_CNSLDTNCOUNTRYTYPE type standard table of TS_I_CNSLDTNCOUNTRYTYPE .
  types:
    begin of TS_I_CNSLDTNCRCYCNVRSNDIFFTYPE.
      include type I_CNSLDTNCRCYCNVRSNDIFFTYPE.
  types:
      T_CURRENCYCONVERSIONSDIFFTYPE type I_CNSLDTNCRCYCNVRSNDIFFTYPET-CURRENCYCONVERSIONSDIFFTYPETXT,
    end of TS_I_CNSLDTNCRCYCNVRSNDIFFTYPE .
  types:
   TT_I_CNSLDTNCRCYCNVRSNDIFFTYPE type standard table of TS_I_CNSLDTNCRCYCNVRSNDIFFTYPE .
  types:
    begin of TS_I_CNSLDTNCUSTOMERTYPE.
      include type I_CNSLDTNCUSTOMER.
  types:
      T_CUSTOMER type I_CNSLDTNCUSTOMERT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNCUSTOMERTYPE .
  types:
   TT_I_CNSLDTNCUSTOMERTYPE type standard table of TS_I_CNSLDTNCUSTOMERTYPE .
  types:
    begin of TS_I_CNSLDTNCUSTOMERGROUPTYPE.
      include type I_CNSLDTNCUSTOMERGROUP.
  types:
      T_CUSTOMERGROUP type I_CNSLDTNCUSTOMERGROUPT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNCUSTOMERGROUPTYPE .
  types:
   TT_I_CNSLDTNCUSTOMERGROUPTYPE type standard table of TS_I_CNSLDTNCUSTOMERGROUPTYPE .
  types:
    begin of TS_I_CNSLDTNDIMENSIONTYPE.
      include type I_CNSLDTNDIMENSION.
  types:
      T_CONSOLIDATIONDIMENSION type I_CNSLDTNDIMENSIONT-CONSOLIDATIONDIMENSIONTEXT,
    end of TS_I_CNSLDTNDIMENSIONTYPE .
  types:
   TT_I_CNSLDTNDIMENSIONTYPE type standard table of TS_I_CNSLDTNDIMENSIONTYPE .
  types:
    begin of TS_I_CNSLDTNDISTRIBUTIONCHANNE.
      include type I_CNSLDTNDISTRIBUTIONCHANNEL.
  types:
      T_DISTRIBUTIONCHANNEL type I_CNSLDTNDISTRIBUTIONCHANNELT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNDISTRIBUTIONCHANNE .
  types:
   TT_I_CNSLDTNDISTRIBUTIONCHANNE type standard table of TS_I_CNSLDTNDISTRIBUTIONCHANNE .
  types:
    begin of TS_I_CNSLDTNDIVISIONTYPE.
      include type I_CNSLDTNDIVISION.
  types:
      T_DIVISION type I_CNSLDTNDIVISIONT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNDIVISIONTYPE .
  types:
   TT_I_CNSLDTNDIVISIONTYPE type standard table of TS_I_CNSLDTNDIVISIONTYPE .
  types:
    begin of TS_I_CNSLDTNDOCUMENTTYPETYPE.
      include type I_CNSLDTNDOCUMENTTYPE.
  types:
      T_CONSOLIDATIONDOCUMENTTYPE type I_CNSLDTNDOCUMENTTYPET-CONSOLIDATIONDOCUMENTTYPETEXT,
    end of TS_I_CNSLDTNDOCUMENTTYPETYPE .
  types:
   TT_I_CNSLDTNDOCUMENTTYPETYPE type standard table of TS_I_CNSLDTNDOCUMENTTYPETYPE .
  types:
   TS_I_CNSLDTNDOCUMENTTYPETTYPE type I_CNSLDTNDOCUMENTTYPET .
  types:
   TT_I_CNSLDTNDOCUMENTTYPETTYPE type standard table of TS_I_CNSLDTNDOCUMENTTYPETTYPE .
  types:
    begin of TS_I_CNSLDTNFINSTMNTITEMTEXTTY.
      include type I_CNSLDTNFINSTMNTITEMTEXT.
  types:
      T_CONSOLIDATIONCHARTOFACCOUNTS type I_CNSLDTNCHARTOFACCOUNTST-CONSOLIDATIONCHARTOFACCTSTEXT,
    end of TS_I_CNSLDTNFINSTMNTITEMTEXTTY .
  types:
   TT_I_CNSLDTNFINSTMNTITEMTEXTTY type standard table of TS_I_CNSLDTNFINSTMNTITEMTEXTTY .
  types:
    begin of TS_I_CNSLDTNFINTRANSTYPETYPE.
      include type I_CNSLDTNFINTRANSTYPE.
  types:
      T_FINANCIALTRANSACTIONTYPE type I_CNSLDTNFINTRANSTYPET-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNFINTRANSTYPETYPE .
  types:
   TT_I_CNSLDTNFINTRANSTYPETYPE type standard table of TS_I_CNSLDTNFINTRANSTYPETYPE .
  types:
    begin of TS_I_CNSLDTNFUNCTIONALAREATYPE.
      include type I_CNSLDTNFUNCTIONALAREA.
  types:
      T_FUNCTIONALAREA type I_CNSLDTNFUNCTIONALAREAT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNFUNCTIONALAREATYPE .
  types:
   TT_I_CNSLDTNFUNCTIONALAREATYPE type standard table of TS_I_CNSLDTNFUNCTIONALAREATYPE .
  types:
    begin of TS_I_CNSLDTNGLACCOUNTTYPE.
      include type I_CNSLDTNGLACCOUNT.
  types:
      T_GLACCOUNT type I_CNSLDTNGLACCOUNTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNGLACCOUNTTYPE .
  types:
   TT_I_CNSLDTNGLACCOUNTTYPE type standard table of TS_I_CNSLDTNGLACCOUNTTYPE .
  types:
    begin of TS_I_CNSLDTNGLCHARTOFACCOUNTST.
      include type I_CNSLDTNGLCHARTOFACCOUNTS.
  types:
      T_CHARTOFACCOUNTS type I_CNSLDTNGLCHARTOFACCOUNTST-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNGLCHARTOFACCOUNTST .
  types:
   TT_I_CNSLDTNGLCHARTOFACCOUNTST type standard table of TS_I_CNSLDTNGLCHARTOFACCOUNTST .
  types:
   TS_I_CNSLDTNGROUPTTYPE type I_CNSLDTNGROUPT .
  types:
   TT_I_CNSLDTNGROUPTTYPE type standard table of TS_I_CNSLDTNGROUPTTYPE .
  types:
    begin of TS_I_CNSLDTNGROUPWITHEMPTYVALU.
      include type I_CNSLDTNGROUPWITHEMPTYVALUE.
  types:
      T_CONSOLIDATIONGROUP type I_CNSLDTNGROUPT-CONSOLIDATIONGROUPTEXT,
    end of TS_I_CNSLDTNGROUPWITHEMPTYVALU .
  types:
   TT_I_CNSLDTNGROUPWITHEMPTYVALU type standard table of TS_I_CNSLDTNGROUPWITHEMPTYVALU .
  types:
    begin of TS_I_CNSLDTNINDUSTRYTYPE.
      include type I_CNSLDTNINDUSTRY.
  types:
      T_INDUSTRY type I_CNSLDTNINDUSTRYT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNINDUSTRYTYPE .
  types:
   TT_I_CNSLDTNINDUSTRYTYPE type standard table of TS_I_CNSLDTNINDUSTRYTYPE .
  types:
    begin of TS_I_CNSLDTNINTERNALORDERTYPE.
      include type I_CNSLDTNINTERNALORDER.
  types:
      T_INTERNALORDER type I_CNSLDTNINTERNALORDERT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNINTERNALORDERTYPE .
  types:
   TT_I_CNSLDTNINTERNALORDERTYPE type standard table of TS_I_CNSLDTNINTERNALORDERTYPE .
  types:
    begin of TS_I_CNSLDTNLEDGERTYPE.
      include type I_CNSLDTNLEDGER.
  types:
      T_CONSOLIDATIONLEDGER type I_CNSLDTNLEDGERT-CONSOLIDATIONLEDGERNAME,
    end of TS_I_CNSLDTNLEDGERTYPE .
  types:
   TT_I_CNSLDTNLEDGERTYPE type standard table of TS_I_CNSLDTNLEDGERTYPE .
  types:
   TS_I_CNSLDTNLEDGERTTYPE type I_CNSLDTNLEDGERT .
  types:
   TT_I_CNSLDTNLEDGERTTYPE type standard table of TS_I_CNSLDTNLEDGERTTYPE .
  types:
    begin of TS_I_CNSLDTNMATERIALTYPE.
      include type I_CNSLDTNMATERIAL.
  types:
      T_MATERIAL type I_CNSLDTNMATERIALT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNMATERIALTYPE .
  types:
   TT_I_CNSLDTNMATERIALTYPE type standard table of TS_I_CNSLDTNMATERIALTYPE .
  types:
    begin of TS_I_CNSLDTNMATERIALGROUPTYPE.
      include type I_CNSLDTNMATERIALGROUP.
  types:
      T_MATERIALGROUP type I_CNSLDTNMATERIALGROUPT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNMATERIALGROUPTYPE .
  types:
   TT_I_CNSLDTNMATERIALGROUPTYPE type standard table of TS_I_CNSLDTNMATERIALGROUPTYPE .
  types:
    begin of TS_I_CNSLDTNPERIODMODETYPE.
      include type I_CNSLDTNPERIODMODE.
  types:
      T_PERIODMODE type I_CNSLDTNPERIODMODETEXT-PERIODMODETEXT,
    end of TS_I_CNSLDTNPERIODMODETYPE .
  types:
   TT_I_CNSLDTNPERIODMODETYPE type standard table of TS_I_CNSLDTNPERIODMODETYPE .
  types:
   TS_I_CNSLDTNPERIODMODETEXTTYPE type I_CNSLDTNPERIODMODETEXT .
  types:
   TT_I_CNSLDTNPERIODMODETEXTTYPE type standard table of TS_I_CNSLDTNPERIODMODETEXTTYPE .
  types:
    begin of TS_I_CNSLDTNPLANTTYPE.
      include type I_CNSLDTNPLANT.
  types:
      T_PLANT type I_CNSLDTNPLANTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNPLANTTYPE .
  types:
   TT_I_CNSLDTNPLANTTYPE type standard table of TS_I_CNSLDTNPLANTTYPE .
  types:
    begin of TS_I_CNSLDTNPOSTINGLEVELTYPE.
      include type I_CNSLDTNPOSTINGLEVEL.
  types:
      T_POSTINGLEVEL type I_CNSLDTNPOSTINGLEVELT-POSTINGLEVELTEXT,
    end of TS_I_CNSLDTNPOSTINGLEVELTYPE .
  types:
   TT_I_CNSLDTNPOSTINGLEVELTYPE type standard table of TS_I_CNSLDTNPOSTINGLEVELTYPE .
  types:
   TS_I_CNSLDTNPOSTINGLEVELTTYPE type I_CNSLDTNPOSTINGLEVELT .
  types:
   TT_I_CNSLDTNPOSTINGLEVELTTYPE type standard table of TS_I_CNSLDTNPOSTINGLEVELTTYPE .
  types:
    begin of TS_I_CNSLDTNPRODUCTTYPE.
      include type I_CNSLDTNPRODUCT.
  types:
      T_PRODUCT type I_CNSLDTNPRODUCTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNPRODUCTTYPE .
  types:
   TT_I_CNSLDTNPRODUCTTYPE type standard table of TS_I_CNSLDTNPRODUCTTYPE .
  types:
    begin of TS_I_CNSLDTNPROFITCENTERTYPE.
      include type I_CNSLDTNPROFITCENTER.
  types:
      T_PROFITCENTER type I_CNSLDTNPROFITCENTERT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNPROFITCENTERTYPE .
  types:
   TT_I_CNSLDTNPROFITCENTERTYPE type standard table of TS_I_CNSLDTNPROFITCENTERTYPE .
  types:
   TS_I_CNSLDTNPROFITCENTERFORELI type I_CNSLDTNPROFITCENTERFORELIMT .
  types:
   TT_I_CNSLDTNPROFITCENTERFORELI type standard table of TS_I_CNSLDTNPROFITCENTERFORELI .
  types:
   TS_I_CNSLDTNPROFITCENTERTTYPE type I_CNSLDTNPROFITCENTERT .
  types:
   TT_I_CNSLDTNPROFITCENTERTTYPE type standard table of TS_I_CNSLDTNPROFITCENTERTTYPE .
  types:
    begin of TS_I_CNSLDTNPROJECTTYPE.
      include type I_CNSLDTNPROJECT.
  types:
      T_PROJECT type I_CNSLDTNPROJECTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNPROJECTTYPE .
  types:
   TT_I_CNSLDTNPROJECTTYPE type standard table of TS_I_CNSLDTNPROJECTTYPE .
  types:
    begin of TS_I_CNSLDTNSALESDISTRICTTYPE.
      include type I_CNSLDTNSALESDISTRICT.
  types:
      T_SALESDISTRICT type I_CNSLDTNSALESDISTRICTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNSALESDISTRICTTYPE .
  types:
   TT_I_CNSLDTNSALESDISTRICTTYPE type standard table of TS_I_CNSLDTNSALESDISTRICTTYPE .
  types:
    begin of TS_I_CNSLDTNSALESORGANIZATIONT.
      include type I_CNSLDTNSALESORGANIZATION.
  types:
      T_SALESORGANIZATION type I_CNSLDTNSALESORGANIZATIONT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNSALESORGANIZATIONT .
  types:
   TT_I_CNSLDTNSALESORGANIZATIONT type standard table of TS_I_CNSLDTNSALESORGANIZATIONT .
  types:
    begin of TS_I_CNSLDTNSEGMENTTYPE.
      include type I_CNSLDTNSEGMENT.
  types:
      T_SEGMENT type I_CNSLDTNSEGMENTT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNSEGMENTTYPE .
  types:
   TT_I_CNSLDTNSEGMENTTYPE type standard table of TS_I_CNSLDTNSEGMENTTYPE .
  types:
   TS_I_CNSLDTNSEGMENTFORELIMTTYP type I_CNSLDTNSEGMENTFORELIMT .
  types:
   TT_I_CNSLDTNSEGMENTFORELIMTTYP type standard table of TS_I_CNSLDTNSEGMENTFORELIMTTYP .
  types:
   TS_I_CNSLDTNSEGMENTTTYPE type I_CNSLDTNSEGMENTT .
  types:
   TT_I_CNSLDTNSEGMENTTTYPE type standard table of TS_I_CNSLDTNSEGMENTTTYPE .
  types:
    begin of TS_I_CNSLDTNSUBITEMTYPE.
      include type I_CNSLDTNSUBITEM.
  types:
      T_SUBITEM type I_CNSLDTNSUBITEMTEXT-SUBITEMTEXT,
    end of TS_I_CNSLDTNSUBITEMTYPE .
  types:
   TT_I_CNSLDTNSUBITEMTYPE type standard table of TS_I_CNSLDTNSUBITEMTYPE .
  types:
    begin of TS_I_CNSLDTNSUBITEMCATEGORYTYP.
      include type I_CNSLDTNSUBITEMCATEGORY.
  types:
      T_SUBITEMCATEGORY type I_CNSLDTNSUBITEMCATEGORYTEXT-SUBITEMCATEGORYTEXT,
    end of TS_I_CNSLDTNSUBITEMCATEGORYTYP .
  types:
   TT_I_CNSLDTNSUBITEMCATEGORYTYP type standard table of TS_I_CNSLDTNSUBITEMCATEGORYTYP .
  types:
    begin of TS_I_CNSLDTNSUPPLIERTYPE.
      include type I_CNSLDTNSUPPLIER.
  types:
      T_SUPPLIER type I_CNSLDTNSUPPLIERT-ADDITIONALMASTERDATATEXT,
    end of TS_I_CNSLDTNSUPPLIERTYPE .
  types:
   TT_I_CNSLDTNSUPPLIERTYPE type standard table of TS_I_CNSLDTNSUPPLIERTYPE .
  types:
   TS_I_CNSLDTNUNITFORELIMINATION type I_CNSLDTNUNITFORELIMINATIONT .
  types:
   TT_I_CNSLDTNUNITFORELIMINATION type standard table of TS_I_CNSLDTNUNITFORELIMINATION .
  types:
   TS_I_CNSLDTNUNITTTYPE type I_CNSLDTNUNITT .
  types:
   TT_I_CNSLDTNUNITTTYPE type standard table of TS_I_CNSLDTNUNITTTYPE .
  types:
    begin of TS_I_CNSLDTNUNIT_2TYPE.
      include type I_CNSLDTNUNIT_2.
  types:
      T_CONSOLIDATIONUNIT type I_CNSLDTNUNITT-CONSOLIDATIONUNITTEXT,
    end of TS_I_CNSLDTNUNIT_2TYPE .
  types:
   TT_I_CNSLDTNUNIT_2TYPE type standard table of TS_I_CNSLDTNUNIT_2TYPE .
  types:
    begin of TS_I_CNSLDTNVERSIONTYPE.
      include type I_CNSLDTNVERSION.
  types:
      T_CONSOLIDATIONVERSION type I_CNSLDTNVERSIONT-CONSOLIDATIONVERSIONTEXT,
    end of TS_I_CNSLDTNVERSIONTYPE .
  types:
   TT_I_CNSLDTNVERSIONTYPE type standard table of TS_I_CNSLDTNVERSIONTYPE .
  types:
   TS_I_CNSLDTNVERSIONTTYPE type I_CNSLDTNVERSIONT .
  types:
   TT_I_CNSLDTNVERSIONTTYPE type standard table of TS_I_CNSLDTNVERSIONTTYPE .
  types:
    begin of TS_I_COMPANYCODETYPE.
      include type I_COMPANYCODE.
  types:
      T_CREDITCONTROLAREA type I_CREDITCONTROLAREATEXT-CREDITCONTROLAREANAME,
      T_CONTROLLINGAREA type I_CONTROLLINGAREA-CONTROLLINGAREANAME,
    end of TS_I_COMPANYCODETYPE .
  types:
   TT_I_COMPANYCODETYPE type standard table of TS_I_COMPANYCODETYPE .
  types:
   TS_I_CONTROLLINGAREASTDVHTYPE type I_CONTROLLINGAREASTDVH .
  types:
   TT_I_CONTROLLINGAREASTDVHTYPE type standard table of TS_I_CONTROLLINGAREASTDVHTYPE .
  types:
    begin of TS_I_CREDITCONTROLAREASTDVHTYP.
      include type I_CREDITCONTROLAREASTDVH.
  types:
      T_CREDITCONTROLAREA type I_CREDITCONTROLAREATEXT-CREDITCONTROLAREANAME,
    end of TS_I_CREDITCONTROLAREASTDVHTYP .
  types:
   TT_I_CREDITCONTROLAREASTDVHTYP type standard table of TS_I_CREDITCONTROLAREASTDVHTYP .
  types:
   TS_I_CREDITCONTROLAREATEXTTYPE type I_CREDITCONTROLAREATEXT .
  types:
   TT_I_CREDITCONTROLAREATEXTTYPE type standard table of TS_I_CREDITCONTROLAREATEXTTYPE .
  types:
    begin of TS_I_CURRENCYTYPE.
      include type I_CURRENCY.
  types:
      T_CURRENCY type I_CURRENCYTEXT-CURRENCYNAME,
    end of TS_I_CURRENCYTYPE .
  types:
   TT_I_CURRENCYTYPE type standard table of TS_I_CURRENCYTYPE .
  types:
    begin of TS_I_DEBITCREDITCODETYPE.
      include type I_DEBITCREDITCODE.
  types:
      T_DEBITCREDITCODE type I_DEBITCREDITCODETEXT-DEBITCREDITCODENAME,
    end of TS_I_DEBITCREDITCODETYPE .
  types:
   TT_I_DEBITCREDITCODETYPE type standard table of TS_I_DEBITCREDITCODETYPE .
  types:
   TS_I_GLOBALCOMPANYTYPE type I_GLOBALCOMPANY .
  types:
   TT_I_GLOBALCOMPANYTYPE type standard table of TS_I_GLOBALCOMPANYTYPE .
  types:
    begin of TS_I_GROUPREPORTINGFSITEMTYPE.
      include type I_GROUPREPORTINGFSITEM.
  types:
      T_CONSOLIDATIONCHARTOFACCOUNTS type I_CNSLDTNCHARTOFACCOUNTST-CONSOLIDATIONCHARTOFACCTSTEXT,
      T_FINANCIALSTATEMENTITEM type I_CNSLDTNFINSTMNTITEMTEXT-FINANCIALSTATEMENTITEMTEXT,
    end of TS_I_GROUPREPORTINGFSITEMTYPE .
  types:
   TT_I_GROUPREPORTINGFSITEMTYPE type standard table of TS_I_GROUPREPORTINGFSITEMTYPE .
  types:
    begin of TS_I_UNITOFMEASURETYPE.
      include type I_UNITOFMEASURE.
  types:
      T_UNITOFMEASURE type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
    end of TS_I_UNITOFMEASURETYPE .
  types:
   TT_I_UNITOFMEASURETYPE type standard table of TS_I_UNITOFMEASURETYPE .

  constants GC_I_CONTROLLINGAREASTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ControllingAreaStdVHType' ##NO_TEXT.
  constants GC_I_COMPANYCODETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CompanyCodeType' ##NO_TEXT.
  constants GC_I_CNSLDTNVERSIONTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnVersionType' ##NO_TEXT.
  constants GC_I_CNSLDTNVERSIONTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnVersionTType' ##NO_TEXT.
  constants GC_I_CNSLDTNUNIT_2TYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnUnit_2Type' ##NO_TEXT.
  constants GC_I_CNSLDTNUNITTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnUnitTType' ##NO_TEXT.
  constants GC_I_CNSLDTNUNITFORELIMINATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnUnitForEliminationTType' ##NO_TEXT.
  constants GC_I_CNSLDTNSUPPLIERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSupplierType' ##NO_TEXT.
  constants GC_I_CNSLDTNSUBITEMTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSubItemType' ##NO_TEXT.
  constants GC_I_CNSLDTNSUBITEMCATEGORYTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSubItemCategoryType' ##NO_TEXT.
  constants GC_I_CNSLDTNSEGMENTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSegmentType' ##NO_TEXT.
  constants GC_I_CNSLDTNSEGMENTTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSegmentTType' ##NO_TEXT.
  constants GC_I_CNSLDTNSEGMENTFORELIMTTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSegmentForElimTType' ##NO_TEXT.
  constants GC_I_CNSLDTNSALESORGANIZATIONT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSalesOrganizationType' ##NO_TEXT.
  constants GC_I_CNSLDTNSALESDISTRICTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnSalesDistrictType' ##NO_TEXT.
  constants GC_I_CNSLDTNPROJECTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnProjectType' ##NO_TEXT.
  constants GC_I_CNSLDTNPROFITCENTERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnProfitCenterType' ##NO_TEXT.
  constants GC_I_CNSLDTNPROFITCENTERTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnProfitCenterTType' ##NO_TEXT.
  constants GC_I_CNSLDTNPROFITCENTERFORELI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnProfitCenterForElimTType' ##NO_TEXT.
  constants GC_I_CNSLDTNPRODUCTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnProductType' ##NO_TEXT.
  constants GC_I_CNSLDTNPOSTINGLEVELTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnPostingLevelType' ##NO_TEXT.
  constants GC_I_CNSLDTNPOSTINGLEVELTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnPostingLevelTType' ##NO_TEXT.
  constants GC_I_CNSLDTNPLANTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnPlantType' ##NO_TEXT.
  constants GC_XEY1XSAV_I_JOURNALENTRYITEM type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_I_JournalEntryItemType' ##NO_TEXT.
  constants GC_XEY1XSAV_I_GLACCTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_I_GlAccTextType' ##NO_TEXT.
  constants GC_XEY1XSAV_I_FSITEMTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_I_FSItemTextType' ##NO_TEXT.
  constants GC_XEY1XSAV_I_ACCCLASSTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_I_AccClassTextType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_RECON_LEDGERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_Recon_LedgerType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_RECON_ADJ_REASON type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_Recon_Adj_ReasonType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_READINTENTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_ReadIntentVHType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_INTENTIONSSTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_IntentionsStatusParameters' ##NO_TEXT.
  constants GC_XEY1XSAV_C_INTENTIONSSTATU type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_IntentionsStatusType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_FETCH_TAX_RATEST type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_Fetch_Tax_RatesType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_FETCH_TAX_RATESP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_Fetch_Tax_RatesParameters' ##NO_TEXT.
  constants GC_XEY1XSAV_C_DEFERREDTAXROLLF type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_DeferredTaxRollFrwdParameters' ##NO_TEXT.
  constants GC_XEY1XSAV_C_DEFERREDTAXROLL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_DeferredTaxRollFrwdResult' ##NO_TEXT.
  constants GC_XEY1XSAV_C_CURRLOCALGROUPVH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_CurrLocalGroupVHType' ##NO_TEXT.
  constants GC_XEY1XSAV_C_CNSLDTNJRNLENTRY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_CnsldtnJrnlEntryParameters' ##NO_TEXT.
  constants GC_XEY1XSAV_C_CNSLDTNJRNLENTR type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'xEY1xSAV_C_CnsldtnJrnlEntryResult' ##NO_TEXT.
  constants GC_I_UNITOFMEASURETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_UnitOfMeasureType' ##NO_TEXT.
  constants GC_I_GROUPREPORTINGFSITEMTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_GroupReportingFSItemType' ##NO_TEXT.
  constants GC_I_GLOBALCOMPANYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_GlobalcompanyType' ##NO_TEXT.
  constants GC_I_DEBITCREDITCODETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_DebitCreditCodeType' ##NO_TEXT.
  constants GC_I_CURRENCYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CurrencyType' ##NO_TEXT.
  constants GC_I_CREDITCONTROLAREATEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CreditControlAreaTextType' ##NO_TEXT.
  constants GC_I_CREDITCONTROLAREASTDVHTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CreditControlAreaStdVHType' ##NO_TEXT.
  constants GC_I_CNSLDTNCOUNTRYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnCountryType' ##NO_TEXT.
  constants GC_I_CNSLDTNCOSTCENTERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnCostCenterType' ##NO_TEXT.
  constants GC_I_CNSLDTNCONTROLLINGAREATYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnControllingAreaType' ##NO_TEXT.
  constants GC_I_CNSLDTNCONTROLLINGAREATTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnControllingAreaTType' ##NO_TEXT.
  constants GC_I_CNSLDTNCHARTOFACCOUNTSTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnChartOfAccountsType' ##NO_TEXT.
  constants GC_I_CNSLDTNCHARTOFACCOUNTSTTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnChartOfAccountsTType' ##NO_TEXT.
  constants GC_I_CNSLDTNBUSINESSAREATYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnBusinessAreaType' ##NO_TEXT.
  constants GC_I_CNSLDTNBILLINGTYPETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnBillingTypeType' ##NO_TEXT.
  constants GC_I_CNSLDTNAPPORTIONMENTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnApportionmentType' ##NO_TEXT.
  constants GC_GLOBALPARAMETER type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'GlobalParameter' ##NO_TEXT.
  constants GC_C_CNSLDTNVERSIONVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnVersionVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNUNITVALUEHELPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnUnitValueHelpType' ##NO_TEXT.
  constants GC_C_CNSLDTNUNITFORELIMINATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnUnitForEliminationVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNSEGMENTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnSegmentVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNSEGMENTFORELIMVHTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnSegmentForElimVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNPROFITCENTERVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnProfitCenterVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNPROFITCENTERFORELI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnProfitCenterForElimVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNPOSTINGLEVELVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnPostingLevelVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNLEDGERVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnLedgerVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNFINSTMNTITEMVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnFinStmntItemVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNDOCUMENTTYPEVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnDocumentTypeVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNCTRLGAREAVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnCtrlgAreaVHType' ##NO_TEXT.
  constants GC_C_CNSLDTNCHARTOFACCOUNTSVHT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_CnsldtnChartOfAccountsVHType' ##NO_TEXT.
  constants GC_I_CNSLDTNPERIODMODETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnPeriodModeType' ##NO_TEXT.
  constants GC_I_CNSLDTNPERIODMODETEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnPeriodModeTextType' ##NO_TEXT.
  constants GC_I_CNSLDTNMATERIALTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnMaterialType' ##NO_TEXT.
  constants GC_I_CNSLDTNMATERIALGROUPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnMaterialGroupType' ##NO_TEXT.
  constants GC_I_CNSLDTNLEDGERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnLedgerType' ##NO_TEXT.
  constants GC_I_CNSLDTNLEDGERTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnLedgerTType' ##NO_TEXT.
  constants GC_I_CNSLDTNINTERNALORDERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnInternalOrderType' ##NO_TEXT.
  constants GC_I_CNSLDTNINDUSTRYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnIndustryType' ##NO_TEXT.
  constants GC_I_CNSLDTNGROUPWITHEMPTYVALU type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnGroupWithEmptyValueType' ##NO_TEXT.
  constants GC_I_CNSLDTNGROUPTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnGroupTType' ##NO_TEXT.
  constants GC_I_CNSLDTNGLCHARTOFACCOUNTST type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnGLChartOfAccountsType' ##NO_TEXT.
  constants GC_I_CNSLDTNGLACCOUNTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnGLAccountType' ##NO_TEXT.
  constants GC_I_CNSLDTNFUNCTIONALAREATYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnFunctionalAreaType' ##NO_TEXT.
  constants GC_I_CNSLDTNFINTRANSTYPETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnFinTransTypeType' ##NO_TEXT.
  constants GC_I_CNSLDTNFINSTMNTITEMTEXTTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnFinStmntItemTextType' ##NO_TEXT.
  constants GC_I_CNSLDTNDOCUMENTTYPETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnDocumentTypeType' ##NO_TEXT.
  constants GC_I_CNSLDTNDOCUMENTTYPETTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnDocumentTypeTType' ##NO_TEXT.
  constants GC_I_CNSLDTNDIVISIONTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnDivisionType' ##NO_TEXT.
  constants GC_I_CNSLDTNDISTRIBUTIONCHANNE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnDistributionChannelType' ##NO_TEXT.
  constants GC_I_CNSLDTNDIMENSIONTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnDimensionType' ##NO_TEXT.
  constants GC_I_CNSLDTNCUSTOMERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnCustomerType' ##NO_TEXT.
  constants GC_I_CNSLDTNCUSTOMERGROUPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnCustomerGroupType' ##NO_TEXT.
  constants GC_I_CNSLDTNCRCYCNVRSNDIFFTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CnsldtnCrcyCnvrsnDiffTypeType' ##NO_TEXT.

  methods LOAD_TEXT_ELEMENTS
  final
    returning
      value(RT_TEXT_ELEMENTS) type TT_TEXT_ELEMENTS
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .

  methods DEFINE
    redefinition .
  methods GET_LAST_MODIFIED
    redefinition .
protected section.
private section.

  methods DEFINE_GLOBALPARAMETER
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods DEFINE_ACTIONS
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods DEFINE_RDS_4
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods GET_LAST_MODIFIED_RDS_4
    returning
      value(RV_LAST_MODIFIED_RDS) type TIMESTAMP .
ENDCLASS.



CLASS /EY1/CL_SAV_DEFERD_TAX_MPC IMPLEMENTATION.


  method DEFINE.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS         &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL  &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                   &*
*&                                                                     &*
*&---------------------------------------------------------------------*

model->set_schema_namespace( 'EY1.SAV_DEFERD_TAX_ROLL_FWD_SRV' ).

define_globalparameter( ).
define_actions( ).
define_rds_4( ).
get_last_modified_rds_4( ).
  endmethod.


  method DEFINE_ACTIONS.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS         &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL  &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                   &*
*&                                                                     &*
*&---------------------------------------------------------------------*


data:
lo_action         type ref to /iwbep/if_mgw_odata_action,                 "#EC NEEDED
lo_parameter      type ref to /iwbep/if_mgw_odata_parameter.              "#EC NEEDED

***********************************************************************************************************************************
*   ACTION - GlobalParameter
***********************************************************************************************************************************

lo_action = model->create_action( 'GlobalParameter' ).  "#EC NOTEXT
*Set return entity type
lo_action->set_return_entity_type( 'GlobalParameter' ). "#EC NOTEXT
*Set HTTP method GET or POST
lo_action->set_http_method( 'GET' ). "#EC NOTEXT
* Set return type multiplicity
lo_action->set_return_multiplicity( '1' ). "#EC NOTEXT
  endmethod.


  method DEFINE_GLOBALPARAMETER.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS         &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL  &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                   &*
*&                                                                     &*
*&---------------------------------------------------------------------*


  data:
        lo_annotation     type ref to /iwbep/if_mgw_odata_annotation,                "#EC NEEDED
        lo_entity_type    type ref to /iwbep/if_mgw_odata_entity_typ,                "#EC NEEDED
        lo_complex_type   type ref to /iwbep/if_mgw_odata_cmplx_type,                "#EC NEEDED
        lo_property       type ref to /iwbep/if_mgw_odata_property,                  "#EC NEEDED
        lo_entity_set     type ref to /iwbep/if_mgw_odata_entity_set.                "#EC NEEDED

***********************************************************************************************************************************
*   ENTITY - GlobalParameter
***********************************************************************************************************************************

lo_entity_type = model->create_entity_type( iv_entity_type_name = 'GlobalParameter' iv_def_entity_set = abap_false ). "#EC NOTEXT

***********************************************************************************************************************************
*Properties
***********************************************************************************************************************************

lo_property = lo_entity_type->create_property( iv_property_name = 'ConsolidationUnit' iv_abap_fieldname = 'CONSOLIDATIONUNIT' ). "#EC NOTEXT
lo_property->set_is_key( ).
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 18 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'FiscalYear' iv_abap_fieldname = 'FISCALYEAR' ). "#EC NOTEXT
lo_property->set_is_key( ).
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 4 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'ConsolidationChartofAccounts' iv_abap_fieldname = 'CONSOLIDATIONCHARTOFACCOUNTS' ). "#EC NOTEXT
lo_property->set_is_key( ).
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 2 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'ConsolidationGroup' iv_abap_fieldname = 'CONSOLIDATIONGROUP' ). "#EC NOTEXT
lo_property->set_is_key( ).
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 18 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'Intention' iv_abap_fieldname = 'INTENTION' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 30 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'PeriodFrom' iv_abap_fieldname = 'PERIODFROM' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 3 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'PeriodTo' iv_abap_fieldname = 'PERIODTO' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 3 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'LocalCurrency' iv_abap_fieldname = 'LOCALCURRENCY' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 5 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'LocalCurrencyType' iv_abap_fieldname = 'LOCALCURRENCYTYPE' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 5 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'GroupCurrency' iv_abap_fieldname = 'GROUPCURRENCY' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 5 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).
lo_property = lo_entity_type->create_property( iv_property_name = 'GroupCurrencyType' iv_abap_fieldname = 'GROUPCURRENCYTYPE' ). "#EC NOTEXT
lo_property->set_type_edm_string( ).
lo_property->set_maxlength( iv_max_length = 5 ). "#EC NOTEXT
lo_property->set_creatable( abap_false ).
lo_property->set_updatable( abap_false ).
lo_property->set_sortable( abap_false ).
lo_property->set_nullable( abap_false ).
lo_property->set_filterable( abap_false ).
lo_property->/iwbep/if_mgw_odata_annotatabl~create_annotation( 'sap' )->add(
      EXPORTING
        iv_key      = 'unicode'
        iv_value    = 'false' ).

lo_entity_type->bind_structure( iv_structure_name  = '/EY1/CL_SAV_DEFERD_TAX_MPC=>TS_GLOBALPARAMETER01' ). "#EC NOTEXT


***********************************************************************************************************************************
*   ENTITY SETS
***********************************************************************************************************************************
lo_entity_set = lo_entity_type->create_entity_set( 'GlobalParameterSet' ). "#EC NOTEXT

lo_entity_set->set_creatable( abap_false ).
lo_entity_set->set_updatable( abap_false ).
lo_entity_set->set_deletable( abap_false ).

lo_entity_set->set_pageable( abap_false ).
lo_entity_set->set_addressable( abap_false ).
lo_entity_set->set_has_ftxt_search( abap_false ).
lo_entity_set->set_subscribable( abap_false ).
lo_entity_set->set_filter_required( abap_false ).
  endmethod.


  method DEFINE_RDS_4.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*
*   This code is generated for Reference Data Source
*   4
*&---------------------------------------------------------------------*
    TRY.
        if_sadl_gw_model_exposure_data~get_model_exposure( )->expose( model )->expose_vocabulary( vocab_anno_model ).
      CATCH cx_sadl_exposure_error INTO DATA(lx_sadl_exposure_error).
        RAISE EXCEPTION TYPE /iwbep/cx_mgw_med_exception
          EXPORTING
            previous = lx_sadl_exposure_error.
    ENDTRY.
  endmethod.


  method GET_LAST_MODIFIED.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS         &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL  &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                   &*
*&                                                                     &*
*&---------------------------------------------------------------------*


  CONSTANTS: lc_gen_date_time TYPE timestamp VALUE '20210823030954'.                  "#EC NOTEXT
 DATA: lv_rds_last_modified TYPE timestamp .
  rv_last_modified = super->get_last_modified( ).
  IF rv_last_modified LT lc_gen_date_time.
    rv_last_modified = lc_gen_date_time.
  ENDIF.
 lv_rds_last_modified =  GET_LAST_MODIFIED_RDS_4( ).
 IF rv_last_modified LT lv_rds_last_modified.
 rv_last_modified  = lv_rds_last_modified .
 ENDIF .
  endmethod.


  method GET_LAST_MODIFIED_RDS_4.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*
*   This code is generated for Reference Data Source
*   4
*&---------------------------------------------------------------------*
*    @@TYPE_SWITCH:
    CONSTANTS: co_gen_date_time TYPE timestamp VALUE '20210823050955'.
    TRY.
        rv_last_modified_rds = CAST cl_sadl_gw_model_exposure( if_sadl_gw_model_exposure_data~get_model_exposure( ) )->get_last_modified( ).
      CATCH cx_root ##CATCH_ALL.
        rv_last_modified_rds = co_gen_date_time.
    ENDTRY.
    IF rv_last_modified_rds < co_gen_date_time.
      rv_last_modified_rds = co_gen_date_time.
    ENDIF.
  endmethod.


  method IF_SADL_GW_MODEL_EXPOSURE_DATA~GET_MODEL_EXPOSURE.
    CONSTANTS: co_gen_timestamp TYPE timestamp VALUE '20210823050955'.
    DATA(lv_sadl_xml) =
               |<?xml version="1.0" encoding="utf-16"?>|  &
               |<sadl:definition xmlns:sadl="http://sap.com/sap.nw.f.sadl" syntaxVersion="V2" >|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_CNSLDTNJRNLENTRY" binding="/EY1/SAV_C_CNSLDTNJRNLENTRY" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCOSTCENTER" binding="I_CNSLDTNCOSTCENTER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCOUNTRY" binding="I_CNSLDTNCOUNTRY" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCRCYCNVRSNDIFFTYPE" binding="I_CNSLDTNCRCYCNVRSNDIFFTYPE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCUSTOMER" binding="I_CNSLDTNCUSTOMER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCUSTOMERGROUP" binding="I_CNSLDTNCUSTOMERGROUP" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNDIMENSION" binding="I_CNSLDTNDIMENSION" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNDISTRIBUTIONCHANNEL" binding="I_CNSLDTNDISTRIBUTIONCHANNEL" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNDIVISION" binding="I_CNSLDTNDIVISION" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNDOCUMENTTYPE" binding="I_CNSLDTNDOCUMENTTYPE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNDOCUMENTTYPET" binding="I_CNSLDTNDOCUMENTTYPET" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNFINSTMNTITEMTEXT" binding="I_CNSLDTNFINSTMNTITEMTEXT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNFINTRANSTYPE" binding="I_CNSLDTNFINTRANSTYPE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNFUNCTIONALAREA" binding="I_CNSLDTNFUNCTIONALAREA" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNGLACCOUNT" binding="I_CNSLDTNGLACCOUNT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNGLCHARTOFACCOUNTS" binding="I_CNSLDTNGLCHARTOFACCOUNTS" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNGROUPT" binding="I_CNSLDTNGROUPT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNGROUPWITHEMPTYVALUE" binding="I_CNSLDTNGROUPWITHEMPTYVALUE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNINDUSTRY" binding="I_CNSLDTNINDUSTRY" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNINTERNALORDER" binding="I_CNSLDTNINTERNALORDER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNLEDGER" binding="I_CNSLDTNLEDGER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNLEDGERT" binding="I_CNSLDTNLEDGERT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNMATERIAL" binding="I_CNSLDTNMATERIAL" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNMATERIALGROUP" binding="I_CNSLDTNMATERIALGROUP" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPERIODMODE" binding="I_CNSLDTNPERIODMODE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPERIODMODETEXT" binding="I_CNSLDTNPERIODMODETEXT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPLANT" binding="I_CNSLDTNPLANT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPOSTINGLEVEL" binding="I_CNSLDTNPOSTINGLEVEL" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPOSTINGLEVELT" binding="I_CNSLDTNPOSTINGLEVELT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPRODUCT" binding="I_CNSLDTNPRODUCT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPROFITCENTER" binding="I_CNSLDTNPROFITCENTER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPROFITCENTERFORELIMT" binding="I_CNSLDTNPROFITCENTERFORELIMT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPROFITCENTERT" binding="I_CNSLDTNPROFITCENTERT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNPROJECT" binding="I_CNSLDTNPROJECT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSALESDISTRICT" binding="I_CNSLDTNSALESDISTRICT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSALESORGANIZATION" binding="I_CNSLDTNSALESORGANIZATION" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSEGMENT" binding="I_CNSLDTNSEGMENT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSEGMENTFORELIMT" binding="I_CNSLDTNSEGMENTFORELIMT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSEGMENTT" binding="I_CNSLDTNSEGMENTT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSUBITEM" binding="I_CNSLDTNSUBITEM" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSUBITEMCATEGORY" binding="I_CNSLDTNSUBITEMCATEGORY" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNSUPPLIER" binding="I_CNSLDTNSUPPLIER" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNUNITFORELIMINATIONT" binding="I_CNSLDTNUNITFORELIMINATIONT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNUNITT" binding="I_CNSLDTNUNITT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNUNIT_2" binding="I_CNSLDTNUNIT_2" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNVERSION" binding="I_CNSLDTNVERSION" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNVERSIONT" binding="I_CNSLDTNVERSIONT" />|  &
               | <sadl:dataSource type="CDS" name="I_COMPANYCODE" binding="I_COMPANYCODE" />| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:dataSource type="CDS" name="I_CONTROLLINGAREASTDVH" binding="I_CONTROLLINGAREASTDVH" />|  &
               | <sadl:dataSource type="CDS" name="I_CREDITCONTROLAREASTDVH" binding="I_CREDITCONTROLAREASTDVH" />|  &
               | <sadl:dataSource type="CDS" name="I_CREDITCONTROLAREATEXT" binding="I_CREDITCONTROLAREATEXT" />|  &
               | <sadl:dataSource type="CDS" name="I_CURRENCY" binding="I_CURRENCY" />|  &
               | <sadl:dataSource type="CDS" name="I_DEBITCREDITCODE" binding="I_DEBITCREDITCODE" />|  &
               | <sadl:dataSource type="CDS" name="I_GLOBALCOMPANY" binding="I_GLOBALCOMPANY" />|  &
               | <sadl:dataSource type="CDS" name="I_GROUPREPORTINGFSITEM" binding="I_GROUPREPORTINGFSITEM" />|  &
               | <sadl:dataSource type="CDS" name="I_UNITOFMEASURE" binding="I_UNITOFMEASURE" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_CURRLOCALGROUPVH" binding="/EY1/SAV_C_CURRLOCALGROUPVH" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_DEFERREDTAXROLLFRWD" binding="/EY1/SAV_C_DEFERREDTAXROLLFRWD" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_FETCH_TAX_RATES" binding="/EY1/SAV_C_FETCH_TAX_RATES" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_INTENTIONSSTATUS" binding="/EY1/SAV_C_INTENTIONSSTATUS" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_READINTENTVH" binding="/EY1/SAV_C_READINTENTVH" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_RECON_ADJ_REASON" binding="/EY1/SAV_C_RECON_ADJ_REASON" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_C_RECON_LEDGER" binding="/EY1/SAV_C_RECON_LEDGER" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_I_ACCCLASSTEXT" binding="/EY1/SAV_I_ACCCLASSTEXT" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_I_FSITEMTEXT" binding="/EY1/SAV_I_FSITEMTEXT" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_I_GLACCTEXT" binding="/EY1/SAV_I_GLACCTEXT" />|  &
               | <sadl:dataSource type="CDS" name="/EY1/SAV_I_JOURNALENTRYITEM" binding="/EY1/SAV_I_JOURNALENTRYITEM" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNCHARTOFACCOUNTSVH" binding="C_CNSLDTNCHARTOFACCOUNTSVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNCTRLGAREAVH" binding="C_CNSLDTNCTRLGAREAVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNDOCUMENTTYPEVH" binding="C_CNSLDTNDOCUMENTTYPEVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNFINSTMNTITEMVH" binding="C_CNSLDTNFINSTMNTITEMVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNLEDGERVH" binding="C_CNSLDTNLEDGERVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNPOSTINGLEVELVH" binding="C_CNSLDTNPOSTINGLEVELVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNPROFITCENTERFORELIMVH" binding="C_CNSLDTNPROFITCENTERFORELIMVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNPROFITCENTERVH" binding="C_CNSLDTNPROFITCENTERVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNSEGMENTFORELIMVH" binding="C_CNSLDTNSEGMENTFORELIMVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNSEGMENTVH" binding="C_CNSLDTNSEGMENTVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNUNITFORELIMINATIONVH" binding="C_CNSLDTNUNITFORELIMINATIONVH" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNUNITVALUEHELP" binding="C_CNSLDTNUNITVALUEHELP" />|  &
               | <sadl:dataSource type="CDS" name="C_CNSLDTNVERSIONVH" binding="C_CNSLDTNVERSIONVH" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNAPPORTIONMENT" binding="I_CNSLDTNAPPORTIONMENT" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNBILLINGTYPE" binding="I_CNSLDTNBILLINGTYPE" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNBUSINESSAREA" binding="I_CNSLDTNBUSINESSAREA" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCHARTOFACCOUNTS" binding="I_CNSLDTNCHARTOFACCOUNTS" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCHARTOFACCOUNTST" binding="I_CNSLDTNCHARTOFACCOUNTST" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCONTROLLINGAREA" binding="I_CNSLDTNCONTROLLINGAREA" />|  &
               | <sadl:dataSource type="CDS" name="I_CNSLDTNCONTROLLINGAREAT" binding="I_CNSLDTNCONTROLLINGAREAT" />|  &
               |<sadl:resultSet>|  &
               |<sadl:structure name="xEY1xSAV_C_CnsldtnJrnlEntryResults" dataSource="/EY1/SAV_C_CNSLDTNJRNLENTRY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               | <sadl:association name="TO_DEBITCREDITCODE" binding="_DEBITCREDITCODE" target="I_DebitCreditCode" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_DIMENSION" binding="_DIMENSION" target="I_CnsldtnDimension" cardinality="one" />|  &
               | <sadl:association name="TO_DISTRIBUTIONCHANNEL" binding="_DISTRIBUTIONCHANNEL" target="I_CnsldtnDistributionChannel" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_DIVISION" binding="_DIVISION" target="I_CnsldtnDivision" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_DOCUMENTTYPE" binding="_DOCUMENTTYPE" target="I_CnsldtnDocumentType" cardinality="one" />|  &
               | <sadl:association name="TO_DOCUMENTTYPETEXT" binding="_DOCUMENTTYPETEXT" target="I_CnsldtnDocumentTypeT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_APPORTIONMENT" binding="_APPORTIONMENT" target="I_CnsldtnApportionment" cardinality="one" />| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:association name="TO_EXTENSION_ACDOCA" binding="_EXTENSION_ACDOCA" target="xEY1xSAV_I_JournalEntryItem" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_FINANCIALSTATEMENTITEMTEXT" binding="_FINANCIALSTATEMENTITEMTEXT" target="I_CnsldtnFinStmntItemText" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_FINANCIALTRANSACTIONTYPE" binding="_FINANCIALTRANSACTIONTYPE" target="I_CnsldtnFinTransType" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_FINSTMNTITM" binding="_FINSTMNTITM" target="I_GroupReportingFSItem" cardinality="one" />|  &
               | <sadl:association name="TO_FUNCTIONALAREA" binding="_FUNCTIONALAREA" target="I_CnsldtnFunctionalArea" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_GLACCOUNTINCHARTOFACCOUNTS" binding="_GLACCOUNTINCHARTOFACCOUNTS" target="I_CnsldtnGLAccount" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CNSLDTNGROUP" binding="_CNSLDTNGROUP" target="I_CnsldtnGroupWithEmptyValue" cardinality="one" />|  &
               | <sadl:association name="TO_GLCHARTOFACCOUNTS" binding="_GLCHARTOFACCOUNTS" target="I_CnsldtnGLChartOfAccounts" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_GROUPCURRENCY" binding="_GROUPCURRENCY" target="I_Currency" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_GROUPTEXT" binding="_GROUPTEXT" target="I_CnsldtnGroupT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_INDUSTRY" binding="_INDUSTRY" target="I_CnsldtnIndustry" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_BASEUNIT" binding="_BASEUNIT" target="I_UnitOfMeasure" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_INTERNALORDER" binding="_INTERNALORDER" target="I_CnsldtnInternalOrder" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CONTROLLINGAREA" binding="_CONTROLLINGAREA" target="I_CnsldtnControllingArea" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_INVESTEEUNIT" binding="_INVESTEEUNIT" target="I_CnsldtnUnit_2" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_LEDGER" binding="_LEDGER" target="I_CnsldtnLedger" cardinality="one" />|  &
               | <sadl:association name="TO_LEDGERTEXT" binding="_LEDGERTEXT" target="I_CnsldtnLedgerT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_LOCALCURRENCY" binding="_LOCALCURRENCY" target="I_Currency" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CNSLDTNSEGMENTELIMINATEDT" binding="_CNSLDTNSEGMENTELIMINATEDT" target="I_CnsldtnSegmentForElimT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_MATERIAL" binding="_MATERIAL" target="I_CnsldtnMaterial" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_MATERIALGROUP" binding="_MATERIALGROUP" target="I_CnsldtnMaterialGroup" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERBUSINESSAREA" binding="_PARTNERBUSINESSAREA" target="I_CnsldtnBusinessArea" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERCOMPANY" binding="_PARTNERCOMPANY" target="I_Globalcompany" cardinality="one" />|  &
               | <sadl:association name="TO_PARTNERCOSTCENTER" binding="_PARTNERCOSTCENTER" target="I_CnsldtnCostCenter" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CONTROLLINGAREATEXT" binding="_CONTROLLINGAREATEXT" target="I_CnsldtnControllingAreaT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_BILLINGDOCUMENTTYPE" binding="_BILLINGDOCUMENTTYPE" target="I_CnsldtnBillingType" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERFUNCTIONALAREA" binding="_PARTNERFUNCTIONALAREA" target="I_CnsldtnFunctionalArea" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERPROFITCENTER" binding="_PARTNERPROFITCENTER" target="I_CnsldtnProfitCenter" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERPROFITCENTERTEXT" binding="_PARTNERPROFITCENTERTEXT" target="I_CnsldtnProfitCenterT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERSEGMENT" binding="_PARTNERSEGMENT" target="I_CnsldtnSegment" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CNSLDTNUNIT" binding="_CNSLDTNUNIT" target="I_CnsldtnUnit_2" cardinality="one" />|  &
               | <sadl:association name="TO_PARTNERSEGMENTTEXT" binding="_PARTNERSEGMENTTEXT" target="I_CnsldtnSegmentT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERUNIT" binding="_PARTNERUNIT" target="I_CnsldtnUnit_2" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PARTNERUNITTEXT" binding="_PARTNERUNITTEXT" target="I_CnsldtnUnitT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PERIODMODETEXT" binding="_PERIODMODETEXT" target="I_CnsldtnPeriodModeText" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_COSTCENTER" binding="_COSTCENTER" target="I_CnsldtnCostCenter" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PLANT" binding="_PLANT" target="I_CnsldtnPlant" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_POSTINGLEVEL" binding="_POSTINGLEVEL" target="I_CnsldtnPostingLevel" cardinality="one" />|  &
               | <sadl:association name="TO_BILLTOPARTY" binding="_BILLTOPARTY" target="I_CnsldtnCustomer" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_POSTINGLEVELTEXT" binding="_POSTINGLEVELTEXT" target="I_CnsldtnPostingLevelT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PROFITCENTER" binding="_PROFITCENTER" target="I_CnsldtnProfitCenter" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PROFITCENTERELIMINATEDT" binding="_PROFITCENTERELIMINATEDT" target="I_CnsldtnProfitCenterForElimT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CNSLDTNUNITELIMINATEDTEXT" binding="_CNSLDTNUNITELIMINATEDTEXT" target="I_CnsldtnUnitForEliminationT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PROFITCENTERTEXT" binding="_PROFITCENTERTEXT" target="I_CnsldtnProfitCenterT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_PROJECT" binding="_PROJECT" target="I_CnsldtnProject" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SALESDISTRICT" binding="_SALESDISTRICT" target="I_CnsldtnSalesDistrict" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_COUNTRY" binding="_COUNTRY" target="I_CnsldtnCountry" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SALESORGANIZATION" binding="_SALESORGANIZATION" target="I_CnsldtnSalesOrganization" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SEGMENT" binding="_SEGMENT" target="I_CnsldtnSegment" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SEGMENTTEXT" binding="_SEGMENTTEXT" target="I_CnsldtnSegmentT" cardinality="zeroToOne" />| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:association name="TO_SHIPTOPARTY" binding="_SHIPTOPARTY" target="I_CnsldtnCustomer" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_BUSINESSAREA" binding="_BUSINESSAREA" target="I_CnsldtnBusinessArea" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SOLDMATERIAL" binding="_SOLDMATERIAL" target="I_CnsldtnMaterial" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SOLDPRODUCT" binding="_SOLDPRODUCT" target="I_CnsldtnProduct" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CNSLDTNUNITTEXT" binding="_CNSLDTNUNITTEXT" target="I_CnsldtnUnitT" cardinality="one" />|  &
               | <sadl:association name="TO_SOLDPRODUCTGROUP" binding="_SOLDPRODUCTGROUP" target="I_CnsldtnMaterialGroup" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SUBITEM" binding="_SUBITEM" target="I_CnsldtnSubItem" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CRCYCNVRSNDIFFTYPE" binding="_CRCYCNVRSNDIFFTYPE" target="I_CnsldtnCrcyCnvrsnDiffType" cardinality="one" />|  &
               | <sadl:association name="TO_SUBITEMCATEGORY" binding="_SUBITEMCATEGORY" target="I_CnsldtnSubItemCategory" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_SUPPLIER" binding="_SUPPLIER" target="I_CnsldtnSupplier" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_TRANSACTIONCURRENCY" binding="_TRANSACTIONCURRENCY" target="I_Currency" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_VERSION" binding="_VERSION" target="I_CnsldtnVersion" cardinality="one" />|  &
               | <sadl:association name="TO_VERSIONTEXT" binding="_VERSIONTEXT" target="I_CnsldtnVersionT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CHARTOFACCOUNTS" binding="_CHARTOFACCOUNTS" target="I_CnsldtnChartOfAccounts" cardinality="one" />|  &
               | <sadl:association name="TO_CHARTOFACCOUNTSTEXT" binding="_CHARTOFACCOUNTSTEXT" target="I_CnsldtnChartOfAccountsT" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_COMPANY" binding="_COMPANY" target="I_Globalcompany" cardinality="one" />|  &
               | <sadl:association name="TO_COMPANYCODE" binding="_COMPANYCODE" target="I_CompanyCode" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CUSTOMER" binding="_CUSTOMER" target="I_CnsldtnCustomer" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_CUSTOMERGROUP" binding="_CUSTOMERGROUP" target="I_CnsldtnCustomerGroup" cardinality="zeroToOne" />|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnCostCenter" dataSource="I_CNSLDTNCOSTCENTER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnCountry" dataSource="I_CNSLDTNCOUNTRY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnCrcyCnvrsnDiffType" dataSource="I_CNSLDTNCRCYCNVRSNDIFFTYPE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnCustomer" dataSource="I_CNSLDTNCUSTOMER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnCustomerGroup" dataSource="I_CNSLDTNCUSTOMERGROUP" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnDimension" dataSource="I_CNSLDTNDIMENSION" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnDistributionChannel" dataSource="I_CNSLDTNDISTRIBUTIONCHANNEL" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnDivision" dataSource="I_CNSLDTNDIVISION" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnDocumentType" dataSource="I_CNSLDTNDOCUMENTTYPE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnDocumentTypeT" dataSource="I_CNSLDTNDOCUMENTTYPET" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnFinStmntItemText" dataSource="I_CNSLDTNFINSTMNTITEMTEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnFinTransType" dataSource="I_CNSLDTNFINTRANSTYPE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnFunctionalArea" dataSource="I_CNSLDTNFUNCTIONALAREA" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnGLAccount" dataSource="I_CNSLDTNGLACCOUNT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnGLChartOfAccounts" dataSource="I_CNSLDTNGLCHARTOFACCOUNTS" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnGroupT" dataSource="I_CNSLDTNGROUPT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnGroupWithEmptyValue" dataSource="I_CNSLDTNGROUPWITHEMPTYVALUE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnIndustry" dataSource="I_CNSLDTNINDUSTRY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnInternalOrder" dataSource="I_CNSLDTNINTERNALORDER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnLedger" dataSource="I_CNSLDTNLEDGER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               |<sadl:structure name="I_CnsldtnLedgerT" dataSource="I_CNSLDTNLEDGERT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnMaterial" dataSource="I_CNSLDTNMATERIAL" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnMaterialGroup" dataSource="I_CNSLDTNMATERIALGROUP" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnPeriodMode" dataSource="I_CNSLDTNPERIODMODE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               | <sadl:association name="TO_TEXT" binding="_TEXT" target="I_CnsldtnPeriodModeText" cardinality="zeroToMany" />|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnPeriodModeText" dataSource="I_CNSLDTNPERIODMODETEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnPlant" dataSource="I_CNSLDTNPLANT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnPostingLevel" dataSource="I_CNSLDTNPOSTINGLEVEL" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnPostingLevelT" dataSource="I_CNSLDTNPOSTINGLEVELT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnProduct" dataSource="I_CNSLDTNPRODUCT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnProfitCenter" dataSource="I_CNSLDTNPROFITCENTER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnProfitCenterForElimT" dataSource="I_CNSLDTNPROFITCENTERFORELIMT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnProfitCenterT" dataSource="I_CNSLDTNPROFITCENTERT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnProject" dataSource="I_CNSLDTNPROJECT" maxEditMode="RO" exposure="TRUE" >| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSalesDistrict" dataSource="I_CNSLDTNSALESDISTRICT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSalesOrganization" dataSource="I_CNSLDTNSALESORGANIZATION" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSegment" dataSource="I_CNSLDTNSEGMENT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSegmentForElimT" dataSource="I_CNSLDTNSEGMENTFORELIMT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSegmentT" dataSource="I_CNSLDTNSEGMENTT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSubItem" dataSource="I_CNSLDTNSUBITEM" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSubItemCategory" dataSource="I_CNSLDTNSUBITEMCATEGORY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnSupplier" dataSource="I_CNSLDTNSUPPLIER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnUnitForEliminationT" dataSource="I_CNSLDTNUNITFORELIMINATIONT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnUnitT" dataSource="I_CNSLDTNUNITT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnUnit_2" dataSource="I_CNSLDTNUNIT_2" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnVersion" dataSource="I_CNSLDTNVERSION" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnVersionT" dataSource="I_CNSLDTNVERSIONT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CompanyCode" dataSource="I_COMPANYCODE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_ControllingAreaStdVH" dataSource="I_CONTROLLINGAREASTDVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CreditControlAreaStdVH" dataSource="I_CREDITCONTROLAREASTDVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               | <sadl:association name="TO_TEXT" binding="_TEXT" target="I_CreditControlAreaText" cardinality="zeroToMany" />|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CreditControlAreaText" dataSource="I_CREDITCONTROLAREATEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_Currency" dataSource="I_CURRENCY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_DebitCreditCode" dataSource="I_DEBITCREDITCODE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_Globalcompany" dataSource="I_GLOBALCOMPANY" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_GroupReportingFSItem" dataSource="I_GROUPREPORTINGFSITEM" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_UnitOfMeasure" dataSource="I_UNITOFMEASURE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_CurrLocalGroupVH" dataSource="/EY1/SAV_C_CURRLOCALGROUPVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_DeferredTaxRollFrwdResults" dataSource="/EY1/SAV_C_DEFERREDTAXROLLFRWD" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               | <sadl:association name="TO_ACCCODE_TEXT" binding="_ACCCODE_TEXT" target="xEY1xSAV_I_AccClassText" cardinality="zeroToOne" />| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:association name="TO_FSITEM_TEXT" binding="_FSITEM_TEXT" target="xEY1xSAV_I_FSItemText" cardinality="zeroToOne" />|  &
               | <sadl:association name="TO_RACCT_TEXT" binding="_RACCT_TEXT" target="xEY1xSAV_I_GlAccText" cardinality="zeroToOne" />|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_Fetch_Tax_RatesSet" dataSource="/EY1/SAV_C_FETCH_TAX_RATES" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_IntentionsStatusSet" dataSource="/EY1/SAV_C_INTENTIONSSTATUS" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_ReadIntentVH" dataSource="/EY1/SAV_C_READINTENTVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_Recon_Adj_Reason" dataSource="/EY1/SAV_C_RECON_ADJ_REASON" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_C_Recon_Ledger" dataSource="/EY1/SAV_C_RECON_LEDGER" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_I_AccClassText" dataSource="/EY1/SAV_I_ACCCLASSTEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_I_FSItemText" dataSource="/EY1/SAV_I_FSITEMTEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_I_GlAccText" dataSource="/EY1/SAV_I_GLACCTEXT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="xEY1xSAV_I_JournalEntryItem" dataSource="/EY1/SAV_I_JOURNALENTRYITEM" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnChartOfAccountsVH" dataSource="C_CNSLDTNCHARTOFACCOUNTSVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnCtrlgAreaVH" dataSource="C_CNSLDTNCTRLGAREAVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnDocumentTypeVH" dataSource="C_CNSLDTNDOCUMENTTYPEVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnFinStmntItemVH" dataSource="C_CNSLDTNFINSTMNTITEMVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnLedgerVH" dataSource="C_CNSLDTNLEDGERVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnPostingLevelVH" dataSource="C_CNSLDTNPOSTINGLEVELVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnProfitCenterForElimVH" dataSource="C_CNSLDTNPROFITCENTERFORELIMVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnProfitCenterVH" dataSource="C_CNSLDTNPROFITCENTERVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnSegmentForElimVH" dataSource="C_CNSLDTNSEGMENTFORELIMVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnSegmentVH" dataSource="C_CNSLDTNSEGMENTVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnUnitForEliminationVH" dataSource="C_CNSLDTNUNITFORELIMINATIONVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnUnitValueHelp" dataSource="C_CNSLDTNUNITVALUEHELP" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="C_CnsldtnVersionVH" dataSource="C_CNSLDTNVERSIONVH" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnApportionment" dataSource="I_CNSLDTNAPPORTIONMENT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnBillingType" dataSource="I_CNSLDTNBILLINGTYPE" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnBusinessArea" dataSource="I_CNSLDTNBUSINESSAREA" maxEditMode="RO" exposure="TRUE" >| .
      lv_sadl_xml = |{ lv_sadl_xml }| &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnChartOfAccounts" dataSource="I_CNSLDTNCHARTOFACCOUNTS" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnChartOfAccountsT" dataSource="I_CNSLDTNCHARTOFACCOUNTST" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnControllingArea" dataSource="I_CNSLDTNCONTROLLINGAREA" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |<sadl:structure name="I_CnsldtnControllingAreaT" dataSource="I_CNSLDTNCONTROLLINGAREAT" maxEditMode="RO" exposure="TRUE" >|  &
               | <sadl:query name="SADL_QUERY">|  &
               | </sadl:query>|  &
               |</sadl:structure>|  &
               |</sadl:resultSet>|  &
               |</sadl:definition>| .

   ro_model_exposure = cl_sadl_gw_model_exposure=>get_exposure_xml( iv_uuid      = CONV #( '/EY1/SAV_DEFERD_TAX_ROLL_FWD' )
                                                                    iv_timestamp = co_gen_timestamp
                                                                    iv_sadl_xml  = lv_sadl_xml ).
  endmethod.


  method LOAD_TEXT_ELEMENTS.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS         &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL  &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                   &*
*&                                                                     &*
*&---------------------------------------------------------------------*


DATA:
     ls_text_element TYPE ts_text_element.                                 "#EC NEEDED
CLEAR ls_text_element.
  endmethod.
ENDCLASS.
